### ISSUE TITLE
PDK convert + CentOS 8 support?

### ISSUE THREAD

**Issue by codylane** [jhoblitt/puppet-ipmi#41]
Hello @jhoblitt,

Thank you so much for your contributions to the puppet community and ecosystem.  

Based off some small testing it doesn't look like it's a lot of work to update to CentOS 8 support.  I'd be happy to help submit a PR for this if you would like? Or if you have time can we put this on the roadmap?

Lastly, I also mentioned PDK, this would be a larger amount of work and but I'd also like to recommend that this module be updated to work with the PDK?  If this is something that you could use help with, I can contribute on that as I have spare time.  Just let me know if you agree and what you might expect a PR to look like for this change.

**Comment by neufeind** [comment]
Needed support for Rocky 8 (RedHat 8) as well, see pull-request https://github.com/jhoblitt/puppet-ipmi/pull/43

**Comment by jhoblitt** [comment]
Resolved by #43.
